FROM alpine:3.19
RUN apk add --no-cache bash curl jq bc postgresql-client openssl docker \
	&& DOCKER_COMPOSE_VERSION="2.27.1" \
	&& curl -SL "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose \
	&& chmod +x /usr/local/bin/docker-compose
WORKDIR /repo
ENTRYPOINT ["/bin/bash"]
CMD ["./run_tests.sh", "--no-start"]