// @generated by diesel — do not edit by hand.
// Reflects migrations/20240101000001_create_schema/up.sql

diesel::table! {
    roles (id) {
        id          -> Uuid,
        name        -> Text,
        description -> Nullable<Text>,
        created_at  -> Timestamptz,
    }
}

diesel::table! {
    org_units (id) {
        id         -> Uuid,
        name       -> Text,
        parent_id  -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    users (id) {
        id                  -> Uuid,
        username            -> Text,
        password_hash       -> Text,
        role_id             -> Uuid,
        org_unit_id         -> Nullable<Uuid>,
        is_active           -> Bool,
        created_at          -> Timestamptz,
        updated_at          -> Timestamptz,
        // Added by migration 00002
        failed_attempts     -> Integer,
        failed_window_start -> Nullable<Timestamptz>,
        locked_until        -> Nullable<Timestamptz>,
        captcha_required    -> Bool,
    }
}

diesel::table! {
    sessions (id) {
        id               -> Uuid,
        user_id          -> Uuid,
        token            -> Text,
        expires_at       -> Timestamptz,
        last_activity_at -> Timestamptz,
        ip_address       -> Nullable<Text>,
        user_agent       -> Nullable<Text>,
        created_at       -> Timestamptz,
        invalidated_at   -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    members (id) {
        id                -> Uuid,
        user_id           -> Uuid,
        org_unit_id       -> Uuid,
        first_name        -> Text,
        last_name         -> Text,
        date_of_birth     -> Date,
        phone             -> Nullable<Text>,
        emergency_contact -> Nullable<Text>,
        created_at        -> Timestamptz,
        updated_at        -> Timestamptz,
    }
}

diesel::table! {
    health_profiles (id) {
        id                   -> Uuid,
        member_id            -> Uuid,
        sex                  -> Text,
        height_in            -> Double,
        weight_lbs           -> Double,
        activity_level       -> Text,
        dietary_notes_enc    -> Nullable<Text>,
        dietary_notes_nonce  -> Nullable<Text>,
        created_at           -> Timestamptz,
        updated_at           -> Timestamptz,
        // Added by migration 00011
        encryption_key_id    -> Text,
        // Added by migration 00013
        medical_notes_enc    -> Nullable<Text>,
        medical_notes_nonce  -> Nullable<Text>,
    }
}

diesel::table! {
    key_rotation_logs (id) {
        id             -> Uuid,
        key_version    -> Text,
        rotated_at     -> Timestamptz,
        rotated_by     -> Nullable<Uuid>,
        notes          -> Nullable<Text>,
        fields_updated -> Integer,
    }
}

diesel::table! {
    metric_types (id) {
        id          -> Uuid,
        name        -> Text,
        unit        -> Text,
        description -> Nullable<Text>,
        is_active   -> Bool,
        created_at  -> Timestamptz,
    }
}

diesel::table! {
    metric_entries (id) {
        id             -> Uuid,
        member_id      -> Uuid,
        metric_type_id -> Uuid,
        value          -> Double,
        entry_date     -> Date,
        recorded_by    -> Uuid,
        notes          -> Nullable<Text>,
        created_at     -> Timestamptz,
    }
}

diesel::table! {
    goals (id) {
        id             -> Uuid,
        member_id      -> Uuid,
        metric_type_id -> Nullable<Uuid>,
        title          -> Text,
        description    -> Nullable<Text>,
        target_value   -> Nullable<Double>,
        target_date    -> Nullable<Date>,
        status         -> Text,
        assigned_by    -> Uuid,
        created_at     -> Timestamptz,
        updated_at     -> Timestamptz,
        // Added by migration 00006
        goal_type      -> Text,
        start_date     -> Date,
        baseline_value -> Double,
    }
}

diesel::table! {
    workflow_templates (id) {
        id            -> Uuid,
        name          -> Text,
        description   -> Nullable<Text>,
        is_active     -> Bool,
        created_by    -> Uuid,
        created_at    -> Timestamptz,
        updated_at    -> Timestamptz,
        // Added by migration 00007
        business_type -> Nullable<Text>,
        org_unit_id   -> Nullable<Uuid>,
        risk_tier     -> Nullable<Text>,
        // Added by migration 00014
        amount_tier   -> Nullable<Text>,
    }
}

diesel::table! {
    workflow_nodes (id) {
        id            -> Uuid,
        template_id   -> Uuid,
        name          -> Text,
        node_order    -> Integer,
        role_required -> Nullable<Uuid>,
        action_type   -> Text,
        created_at    -> Timestamptz,
        // Added by migration 00007
        is_parallel   -> Bool,
    }
}

diesel::table! {
    work_orders (id) {
        id          -> Uuid,
        member_id   -> Uuid,
        title       -> Text,
        description -> Nullable<Text>,
        priority    -> Text,
        status      -> Text,
        assigned_to -> Nullable<Uuid>,
        created_by  -> Uuid,
        due_date    -> Nullable<Date>,
        created_at  -> Timestamptz,
        updated_at  -> Timestamptz,
        // Added by migration 00008
        ticket_type           -> Nullable<Text>,
        processing_notes      -> Nullable<Text>,
        routed_to_org_unit_id -> Nullable<Uuid>,
        resolved_at           -> Nullable<Timestamptz>,
        closed_at             -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    workflow_instances (id) {
        id              -> Uuid,
        template_id     -> Uuid,
        work_order_id   -> Nullable<Uuid>,
        current_node_id -> Nullable<Uuid>,
        status          -> Text,
        initiated_by    -> Uuid,
        created_at      -> Timestamptz,
        updated_at      -> Timestamptz,
        // Added by migration 00007
        current_stage   -> Nullable<Integer>,
        submitted_at    -> Nullable<Timestamptz>,
        completed_at    -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    approvals (id) {
        id                   -> Uuid,
        workflow_instance_id -> Uuid,
        node_id              -> Uuid,
        approver_id          -> Uuid,
        status               -> Text,
        comments             -> Nullable<Text>,
        decided_at           -> Nullable<Timestamptz>,
        created_at           -> Timestamptz,
        // Added by migration 00007
        sla_deadline         -> Nullable<Timestamptz>,
        sla_breached         -> Bool,
        assignee_id          -> Nullable<Uuid>,
        note                 -> Nullable<Text>,
    }
}

diesel::table! {
    notification_templates (id) {
        id            -> Uuid,
        name          -> Text,
        subject       -> Text,
        body_template -> Text,
        created_at    -> Timestamptz,
        updated_at    -> Timestamptz,
    }
}

diesel::table! {
    notifications (id) {
        id          -> Uuid,
        user_id     -> Uuid,
        template_id -> Nullable<Uuid>,
        title       -> Text,
        body        -> Text,
        is_read     -> Bool,
        created_at  -> Timestamptz,
        // Added by migration 00009
        read_at     -> Nullable<Timestamptz>,
        event_type  -> Nullable<Text>,
        entity_type -> Nullable<Text>,
        entity_id   -> Nullable<Uuid>,
    }
}

diesel::table! {
    deliveries (id) {
        id              -> Uuid,
        notification_id -> Uuid,
        channel         -> Text,
        status          -> Text,
        delivered_at    -> Nullable<Timestamptz>,
        created_at      -> Timestamptz,
        // Added by migration 00009
        attempt_count   -> Integer,
        next_attempt_at -> Nullable<Timestamptz>,
        last_error      -> Nullable<Text>,
    }
}

diesel::table! {
    notification_subscriptions (id) {
        id            -> Uuid,
        user_id       -> Uuid,
        event_type    -> Text,
        is_subscribed -> Bool,
        created_at    -> Timestamptz,
        updated_at    -> Timestamptz,
    }
}

diesel::table! {
    notification_schedules (id) {
        id                -> Uuid,
        user_id           -> Uuid,
        template_id       -> Nullable<Uuid>,
        label             -> Text,
        fire_hour         -> Integer,
        tz_offset_minutes -> Integer,
        is_active         -> Bool,
        last_fired_at     -> Nullable<Timestamptz>,
        next_fire_at      -> Timestamptz,
        created_at        -> Timestamptz,
        updated_at        -> Timestamptz,
    }
}

diesel::table! {
    audit_logs (id) {
        id          -> Uuid,
        actor_id    -> Nullable<Uuid>,
        action      -> Text,
        entity_type -> Text,
        entity_id   -> Nullable<Uuid>,
        old_value   -> Nullable<Jsonb>,
        new_value   -> Nullable<Jsonb>,
        ip_address  -> Nullable<Text>,
        created_at  -> Timestamptz,
        // Added by migration 00012
        reason_code -> Nullable<Text>,
        old_hash    -> Nullable<Text>,
        new_hash    -> Nullable<Text>,
    }
}

diesel::joinable!(sessions -> users (user_id));

// ── Foreign-key join helpers ─────────────────────────────────
// Where a table has two FKs to the same table (e.g. work_orders
// → users via created_by AND assigned_to), only one joinable! is
// registered; the other FK is used via explicit join predicates.

diesel::joinable!(users             -> roles                (role_id));
diesel::joinable!(users             -> org_units            (org_unit_id));
diesel::joinable!(members           -> users                (user_id));
diesel::joinable!(members           -> org_units            (org_unit_id));
diesel::joinable!(health_profiles   -> members              (member_id));
diesel::joinable!(metric_entries    -> members              (member_id));
diesel::joinable!(metric_entries    -> metric_types         (metric_type_id));
diesel::joinable!(metric_entries    -> users                (recorded_by));
diesel::joinable!(goals             -> members              (member_id));
diesel::joinable!(goals             -> metric_types         (metric_type_id));
diesel::joinable!(goals             -> users                (assigned_by));
diesel::joinable!(workflow_templates -> users               (created_by));
diesel::joinable!(workflow_nodes    -> workflow_templates   (template_id));
diesel::joinable!(workflow_nodes    -> roles                (role_required));
diesel::joinable!(work_orders       -> members              (member_id));
diesel::joinable!(work_orders       -> users                (created_by));
diesel::joinable!(workflow_instances -> workflow_templates  (template_id));
diesel::joinable!(workflow_instances -> work_orders         (work_order_id));
diesel::joinable!(workflow_instances -> workflow_nodes      (current_node_id));
diesel::joinable!(workflow_instances -> users               (initiated_by));
diesel::joinable!(approvals         -> workflow_instances   (workflow_instance_id));
diesel::joinable!(approvals         -> workflow_nodes       (node_id));
diesel::joinable!(approvals         -> users                (approver_id));
diesel::joinable!(notifications              -> users                  (user_id));
diesel::joinable!(notifications              -> notification_templates  (template_id));
diesel::joinable!(deliveries                 -> notifications           (notification_id));
diesel::joinable!(notification_subscriptions -> users                   (user_id));
diesel::joinable!(notification_schedules     -> users                   (user_id));
diesel::joinable!(notification_schedules     -> notification_templates  (template_id));
diesel::joinable!(audit_logs                 -> users                   (actor_id));
diesel::joinable!(key_rotation_logs          -> users                   (rotated_by));

diesel::allow_tables_to_appear_in_same_query!(
    roles,
    org_units,
    users,
    members,
    health_profiles,
    metric_types,
    metric_entries,
    goals,
    workflow_templates,
    workflow_nodes,
    work_orders,
    workflow_instances,
    approvals,
    notification_templates,
    notifications,
    deliveries,
    notification_subscriptions,
    notification_schedules,
    sessions,
    audit_logs,
    key_rotation_logs,
);
